/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as AdminSnapshotsRouteImport } from './routes/admin.snapshots'
import { Route as ApiSyncStockRouteImport } from './routes/api/sync/stock'
import { Route as ApiSyncCustomersRouteImport } from './routes/api/sync/customers'
import { Route as ApiSyncContractsRouteImport } from './routes/api/sync/contracts'
import { Route as ApiDiagnosticsPreviewRouteImport } from './routes/api/diagnostics/preview'
import { Route as ApiDiagnosticsHealthRouteImport } from './routes/api/diagnostics/health'
import { Route as ApiDiagnosticsTypeRouteImport } from './routes/api/diagnostics/$type'
import { Route as ApiAuthConnectRouteImport } from './routes/api/auth/connect'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSnapshotsRoute = AdminSnapshotsRouteImport.update({
  id: '/admin/snapshots',
  path: '/admin/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncStockRoute = ApiSyncStockRouteImport.update({
  id: '/api/sync/stock',
  path: '/api/sync/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncCustomersRoute = ApiSyncCustomersRouteImport.update({
  id: '/api/sync/customers',
  path: '/api/sync/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncContractsRoute = ApiSyncContractsRouteImport.update({
  id: '/api/sync/contracts',
  path: '/api/sync/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsPreviewRoute = ApiDiagnosticsPreviewRouteImport.update({
  id: '/api/diagnostics/preview',
  path: '/api/diagnostics/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsHealthRoute = ApiDiagnosticsHealthRouteImport.update({
  id: '/api/diagnostics/health',
  path: '/api/diagnostics/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsTypeRoute = ApiDiagnosticsTypeRouteImport.update({
  id: '/api/diagnostics/$type',
  path: '/api/diagnostics/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConnectRoute = ApiAuthConnectRouteImport.update({
  id: '/api/auth/connect',
  path: '/api/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
  '/admin/snapshots': typeof AdminSnapshotsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/diagnostics/$type': typeof ApiDiagnosticsTypeRoute
  '/api/diagnostics/health': typeof ApiDiagnosticsHealthRoute
  '/api/diagnostics/preview': typeof ApiDiagnosticsPreviewRoute
  '/api/sync/contracts': typeof ApiSyncContractsRoute
  '/api/sync/customers': typeof ApiSyncCustomersRoute
  '/api/sync/stock': typeof ApiSyncStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
  '/admin/snapshots': typeof AdminSnapshotsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/diagnostics/$type': typeof ApiDiagnosticsTypeRoute
  '/api/diagnostics/health': typeof ApiDiagnosticsHealthRoute
  '/api/diagnostics/preview': typeof ApiDiagnosticsPreviewRoute
  '/api/sync/contracts': typeof ApiSyncContractsRoute
  '/api/sync/customers': typeof ApiSyncCustomersRoute
  '/api/sync/stock': typeof ApiSyncStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
  '/admin/snapshots': typeof AdminSnapshotsRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/diagnostics/$type': typeof ApiDiagnosticsTypeRoute
  '/api/diagnostics/health': typeof ApiDiagnosticsHealthRoute
  '/api/diagnostics/preview': typeof ApiDiagnosticsPreviewRoute
  '/api/sync/contracts': typeof ApiSyncContractsRoute
  '/api/sync/customers': typeof ApiSyncCustomersRoute
  '/api/sync/stock': typeof ApiSyncStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/invoices'
    | '/settings'
    | '/stock'
    | '/users'
    | '/admin/snapshots'
    | '/api/proxy'
    | '/api/auth/connect'
    | '/api/diagnostics/$type'
    | '/api/diagnostics/health'
    | '/api/diagnostics/preview'
    | '/api/sync/contracts'
    | '/api/sync/customers'
    | '/api/sync/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/invoices'
    | '/settings'
    | '/stock'
    | '/users'
    | '/admin/snapshots'
    | '/api/proxy'
    | '/api/auth/connect'
    | '/api/diagnostics/$type'
    | '/api/diagnostics/health'
    | '/api/diagnostics/preview'
    | '/api/sync/contracts'
    | '/api/sync/customers'
    | '/api/sync/stock'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/invoices'
    | '/settings'
    | '/stock'
    | '/users'
    | '/admin/snapshots'
    | '/api/proxy'
    | '/api/auth/connect'
    | '/api/diagnostics/$type'
    | '/api/diagnostics/health'
    | '/api/diagnostics/preview'
    | '/api/sync/contracts'
    | '/api/sync/customers'
    | '/api/sync/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  InvoicesRoute: typeof InvoicesRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  UsersRoute: typeof UsersRoute
  AdminSnapshotsRoute: typeof AdminSnapshotsRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiAuthConnectRoute: typeof ApiAuthConnectRoute
  ApiDiagnosticsTypeRoute: typeof ApiDiagnosticsTypeRoute
  ApiDiagnosticsHealthRoute: typeof ApiDiagnosticsHealthRoute
  ApiDiagnosticsPreviewRoute: typeof ApiDiagnosticsPreviewRoute
  ApiSyncContractsRoute: typeof ApiSyncContractsRoute
  ApiSyncCustomersRoute: typeof ApiSyncCustomersRoute
  ApiSyncStockRoute: typeof ApiSyncStockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/snapshots': {
      id: '/admin/snapshots'
      path: '/admin/snapshots'
      fullPath: '/admin/snapshots'
      preLoaderRoute: typeof AdminSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/stock': {
      id: '/api/sync/stock'
      path: '/api/sync/stock'
      fullPath: '/api/sync/stock'
      preLoaderRoute: typeof ApiSyncStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/customers': {
      id: '/api/sync/customers'
      path: '/api/sync/customers'
      fullPath: '/api/sync/customers'
      preLoaderRoute: typeof ApiSyncCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/contracts': {
      id: '/api/sync/contracts'
      path: '/api/sync/contracts'
      fullPath: '/api/sync/contracts'
      preLoaderRoute: typeof ApiSyncContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics/preview': {
      id: '/api/diagnostics/preview'
      path: '/api/diagnostics/preview'
      fullPath: '/api/diagnostics/preview'
      preLoaderRoute: typeof ApiDiagnosticsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics/health': {
      id: '/api/diagnostics/health'
      path: '/api/diagnostics/health'
      fullPath: '/api/diagnostics/health'
      preLoaderRoute: typeof ApiDiagnosticsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics/$type': {
      id: '/api/diagnostics/$type'
      path: '/api/diagnostics/$type'
      fullPath: '/api/diagnostics/$type'
      preLoaderRoute: typeof ApiDiagnosticsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/connect': {
      id: '/api/auth/connect'
      path: '/api/auth/connect'
      fullPath: '/api/auth/connect'
      preLoaderRoute: typeof ApiAuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  InvoicesRoute: InvoicesRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  UsersRoute: UsersRoute,
  AdminSnapshotsRoute: AdminSnapshotsRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiAuthConnectRoute: ApiAuthConnectRoute,
  ApiDiagnosticsTypeRoute: ApiDiagnosticsTypeRoute,
  ApiDiagnosticsHealthRoute: ApiDiagnosticsHealthRoute,
  ApiDiagnosticsPreviewRoute: ApiDiagnosticsPreviewRoute,
  ApiSyncContractsRoute: ApiSyncContractsRoute,
  ApiSyncCustomersRoute: ApiSyncCustomersRoute,
  ApiSyncStockRoute: ApiSyncStockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
