/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiAuthConnectRouteImport } from './routes/api/auth/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConnectRoute = ApiAuthConnectRouteImport.update({
  id: '/api/auth/connect',
  path: '/api/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/proxy' | '/api/auth/connect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/proxy' | '/api/auth/connect'
  id: '__root__' | '/' | '/api/proxy' | '/api/auth/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiAuthConnectRoute: typeof ApiAuthConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/connect': {
      id: '/api/auth/connect'
      path: '/api/auth/connect'
      fullPath: '/api/auth/connect'
      preLoaderRoute: typeof ApiAuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiAuthConnectRoute: ApiAuthConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
